<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMvmor6o\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMvmor6o/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMvmor6o.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMvmor6o\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMvmor6o\appProdProjectContainer(array(
    'container.build_hash' => 'Mvmor6o',
    'container.build_id' => '2b7e73f9',
    'container.build_time' => 1532936693,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMvmor6o');
